# Generated by Django 4.2.15 on 2024-08-16 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_rename_tite_question_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='priotity',
            new_name='priority',
        ),
    ]
